import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Styles.module.css";

export default function MainLayout({ children, title = "Create next app" }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{children}</main>
    </div>
  );
}
